name: Update verovio

on:
    schedule:
        - cron:  '0 0 * * *'
    workflow_dispatch: ~

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            -
                name: Build docker image
                run: docker build -t verovio-script -f Dockerfile .
            -
                name: Copy wasm
                run: |
                    git checkout gh-pages
                    docker create --name dummy verovio-script
                    docker cp dummy:/app/verovio-toolkit-wasm.js scripts/verovio-toolkit-wasm.js
                    docker rm -f dummy
            -
                name: Commit changes
                run: |
                    git config --global user.name "Wolfgang Drescher"
                    git config --global user.email "drescher.wolfgang+git@gmail.com"
                    git diff --quiet && git diff --staged --quiet || git commit -am "Update"
                    git push

